### ISSUE TITLE
Deploy is failing

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/sandbox#14]
https://github.com/Islandora-Devops/sandbox/actions/runs/8031018512

failed to deploy to test.islandora.ca

and then I tried to run manually here: https://github.com/Islandora-Devops/sandbox/actions/runs/8033301718

Not sure what is going on, I no longer have access to bitwarden, etc so I can't checkout out digital ocean. @ajstanley mind taking a look?

**Comment by ajstanley** [comment]
The error is an odd one -
```
Error: POST https://api.digitalocean.com/v2/droplets: 422 (request "e6bb992e-6551-44f4-bb97-12335e2617c4") Size is not available in this region.
Error: Process completed with exit code 1.
```
As far as I know, nothing has changed in our configs.  I'll see if I can track this one down.

**Comment by misilot** [comment]
Could it have been a capacity issue at the time?

Might be just worth restarting the workflow?

**Comment by ajstanley** [comment]
That was my thought as well, but I saw the same error on a retry.  The issue seems to come from [here](https://github.com/Islandora-Devops/sandbox/blob/main/.github/workflows/create.yml#L81rl) with a mismatch between region and size.  I'm guessing Digital Ocean has changed what's available where.

**Comment by nigelgbanks** [comment]
https://test.islandora.ca/ isn't up although the deployment said it was.

**Comment by ajstanley** [comment]
It shows an attempt to build the Droplet, but fails after about a minute with the same region/size error.    I'm trying to track down where the variables are set.

**Comment by misilot** [comment]
https://github.com/Islandora-Devops/sandbox/settings/variables/actions
possibly?

**Comment by nigelgbanks** [comment]
I changed it to use AMD since intel wasn't available any more. Running it now: https://github.com/Islandora-Devops/sandbox/actions/runs/8040381065

**Comment by nigelgbanks** [comment]
It's working now! Cheers @ajstanley & @misilot

**Comment by ajstanley** [comment]
NIce one!  Thanks @nigelgbanks
