### ISSUE TITLE
Snapshot got deleted? Can no longer deploy.

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/sandbox#18]
"Get Snapshot ID" Seems to have failed, was it deleted? I don't have access to the digital ocean account anymore, so I do not know.

https://github.com/Islandora-Devops/sandbox/actions/runs/8907125963/job/24460692910

If that's the case, I'll need access again to re-create it.

**Comment by ajstanley** [comment]
Something bad has happened to the server.  When I checked in a few key executables, most notably dnf and doctl, were not there.  I've reinstalled doctl, and issued a new authentication token for it.
The snapshot we had been using for that build is not there.  Our only snapshot is a year old

**Comment by ajstanley** [comment]
All good now.  Thanks Nigel!
